version: "1.0"
info:
  model: int-scaffold
packages:
- name: TheoExtProject
  gitServerName: TheoGit
  gitUrl: https://github.com/theoezell/TheoExtProject
  gitUsername: theoezell
  gitBranch: main
- name: Utilities
  gitServerName: TheoGit
  gitUrl: https://github.com/theoezell
  gitUsername: theoezell
  gitBranch: master
services:
- serviceName: project.theoext.integrations:firstTestFlow
  packages:
  - name: TheoExtProject
    version: "1.0"
  - name: Utilities
    version: "1.0"
- serviceName: Utilities:isEvenNumber
  packages:
  - name: Utilities
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.math:divideFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.theoext.integrations:testJDBC
  packages:
  - name: TheoExtProject
    version: "1.0"
  - name: Utilities
    version: "1.0"
